### ISSUE TITLE
[FEATURE] Expose GTK CMake options as cargo feature

### ISSUE THREAD

**Issue by nohsheef** [fltk-rs/fltk-rs#1429]
**Is your feature request related to a problem? Please describe.**
Avoid linking against GTK in apps that don't need it.

**Describe the solution you'd like**
As discussed in https://github.com/fltk/fltk/issues/746, there are CMake options to turn off linking against GTK and loading GTK functions at runtime. We should be able to expose that as a combined cargo feature.

```
-DOPTION_ALLOW_GTK_PLUGIN=OFF
-DOPTION_FNFC_USES_GTK=OFF
-DOPTION_PRINTER_USES_GTK=OFF
```

Unsure what to name the cargo feature. Since these are enabled automatically right now, I don't think `use-gtk` defaulting to true would make sense. However, `without-gtk` doesn't seem idiomatic, yet I don't have a better suggestion so far.

**Comment by MoAlyousef** [comment]
The linking to libgtk on wayland was required because of libdecor. I've updated the build script to avoid linking libgtk.
Can you try with the master branch?

OPTION_FNFC_USES_GTK is not a CMake option, neither is OPTION_PRINTER_USES_GTK. They're options which can be set at runtime. I've also added that capability:
```rust
    app::set_option(app::Option::FnfcUsesZenity, true);
```

**Comment by nohsheef** [comment]
It's possible my memory was wrong. 1.4.7 with `use-wayland,use-ninja,enable-glwindow` doesn't appear to link against GTK at build time. Sorry. Yet this ticket resulted in new runtime tweak functions, so it wasn't pointless.
