### ISSUE TITLE
[BUG] Memory leak at Fl_text_buffer::text

### ISSUE THREAD

**Issue by WhiteBlackGoose** [fltk-rs/fltk-rs#1454]
Repeated setting buffer to `TextDisplay` causes ever growing memory consumption

## To Reproduce
```rs
use fltk::{*, prelude::{WidgetBase, WindowExt, DisplayExt, GroupExt, WidgetExt}};

fn main() {
    let app = app::App::default();
    let mut wind = window::Window::new(0, 0, 400, 400, "Memory Leak Repro").center_screen();
    let mut text = text::TextDisplay::new(0, 0, 400, 400, "");
    wind.end();
    wind.show();
    let s = "hello world!".repeat(10000);
    while app.wait() {
        let mut buf = text::TextBuffer::default();
        buf.set_text(s.as_str());
        text.set_buffer(buf);
    }
}
```

## Screenshots

`heaptrack` report

![image](https://github.com/fltk-rs/fltk-rs/assets/31178401/4478c3ca-9e46-4688-ad26-b0b776ebdd07)

## Desktop info
 - OS: NixOS unstable
 - Display server: x11

**Comment by MoAlyousef** [comment]
Does the following program also leak?
```rust
use fltk::{*, prelude::{WidgetBase, WindowExt, DisplayExt, GroupExt, WidgetExt}};

fn main() {
    let app = app::App::default();
    let mut wind = window::Window::new(0, 0, 400, 400, "Memory Leak Repro").center_screen();
    let mut text = text::TextDisplay::new(0, 0, 400, 400, "");
    wind.end();
    wind.show();
    let s = "hello world!".repeat(100000);
    let mut buf = text::TextBuffer::default();
    text.set_buffer(buf.clone());
    while app.wait() {
        buf.set_text(s.as_str());
    }
}
```

In your program, the leak happens because once a buffer is passed to a DisplayExt widget, fltk-rs has no way of determining when its lifetime ends. So basically in the while loop, the buffer isn't dropped. Actually dropping it will dangle its reference in the TextDisplay and cause a use-after-free.
I'm not sure how to fix this in fltk-rs which ensures RAII for the TextBuffer. My current recommendation is to treat a TextBuffer passed to a widget as a long living object which should be alive for the lifetime of the program. 
Any other suggestions are welcome

**Comment by WhiteBlackGoose** [comment]
Beat me to it by 2 minutes! I just figured myself how to avoid the leak and was about to post it haha. Thank you for the info. I'll need to be more careful about creating objects xD
