### ISSUE TITLE
[BUG] build failed

### ISSUE THREAD

**Issue by rubenh2905** [fltk-rs/fltk-rs#1459]
logs was too long (over 90k characters)
logs:
[logs.txt](https://github.com/fltk-rs/fltk-rs/files/12598482/logs.txt)

OS info:
```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎5/‎13/‎2023
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0
```

![image](https://github.com/fltk-rs/fltk-rs/assets/85017677/b1dec07c-3982-4eee-a3ab-057f0e26e3bd)

TLDR:
at first i'm was trying ro build for "aarch64-linux-android" target (staticlib using cargo build and cdylib using cargo-ndk (cargo ndk -t ... build ) both have same issue) but when i get a lot of nonsense error for cfltk missing i tryed to repeate `.github/workflows/rust.yml` to just clone recursive and build examples (you can see steps on logs.txt file) and get error on 
```
FAILED: fltk/png/CMakeFiles/fltk_png.dir/png.c.obj
```
several month ago when i'm was trying to learn how i can use it for windows desktop i had the same issue that cfltk was not building but it just majically fixed idk how so i thud it was a bug in the crate version and master branch on github was fixed, but now non of them working ether for desktop or android targets.

simplly cfltk is not building for me for some unknown reasons

**Comment by MoAlyousef** [comment]
Hi
Thanks for the log and the report. 

I think the reason is that the vcpkg include path is listed before the fltk include paths. Not sure why that is, maybe when you do a `vcpkg integrate` it does that. 
This leads to the builtin png lib to include a mismatched zlib header (the one from vcpkg). 

Proposed solutions:
- do a `vcpkg integrate uninstall` then a clean rebuild of fltk. Or:
- Use the fltk-bundled feature which will download a prebuilt cfltk for your system. Or:
- Use libpng and zlib installed via vcpkg and set system-png and system-zlib features to true.

**Comment by rubenh2905** [comment]
[config.toml.txt](https://github.com/fltk-rs/fltk-rs/files/12599709/config.toml.txt)
[Cargo.toml.txt](https://github.com/fltk-rs/fltk-rs/files/12599710/Cargo.toml.txt)
[android-logs.txt](https://github.com/fltk-rs/fltk-rs/files/12599711/android-logs.txt)

**Comment by MoAlyousef** [comment]
FLTK upstream removed android support (temporarily to improve things). You could try setting the version to "=1.2.21". Versions after 1.2.28 don’t support android.
