### ISSUE TITLE
[BUG]  assert failure in Terminal::selection_text()

### ISSUE THREAD

**Issue by jgriffitts** [fltk-rs/fltk-rs#1503]
## Describe the bug
The `assert!(self.is_derived);` at the first line of selection_text() sometimes fails. In at least some cases, it is because `self` is a Widget_Tracker which is not "derived".

## To Reproduce
Execute `dbg!(term.selection_text());` within a `term.handle()` closure where `term` in an instance of group::experimental::Terminal.

## Expected behavior
Obviously, I don't expect the assert to fail. I have not seen any ill effects from commenting out the assert line, but I don't understand what `is_derived`  does so I don't know if this is safe.

## Desktop info
 - OS: [e.g. Windows 10 x64, macOS 10.15, Ubuntu 18.04 x64]
 - Version [e.g. 1.4.2]
 - Display server on linux (wayland or x11)

## Desktop info
 - OS: [e.g. Windows 10 x64, macOS 10.15, Ubuntu 18.04 x64]
 - Version [e.g. 1.4.2]
 - Display server on linux (wayland or x11)

**Comment by MoAlyousef** [comment]
Basically protected methods are exposed by creating similarly named methods on a derived class and making those public. These are new methods which don't exist in the base class. So for example, if FLTK hands you a Window that it has instantiated (not you using fltk-rs, as in the case of a dialog for example), and you call force_position() or set_alpha() which is a protected method. The c bindings will cast the Fl_Double_Window pointer to an Fl_Double_Window_Derived pointer and call that method which doesn't really exist for Fl_Double_Window, which is thus UB.

```rust
let fc = FileChooser::new(/*args*/);
let mut win = fc.window();
win.set_alpha(0.5); // undefined
let prev_btn = fc.preview_button().unwrap();
prev_btn.handle(|b, ev| false); // undefined
```
That's because these widgets were created by FLTK and not fltk-rs.

The workaround is to call assume_derived() which is unsafe.

**Comment by MoAlyousef** [comment]
I have added assume_derived() in the handle(), draw() and set_callback() methods.
