### ISSUE TITLE
Creating an RBG image with custom line depth

### ISSUE THREAD

**Issue by rhelmot** [fltk-rs/fltk-rs#657]
Is there an binding for the C++ [Fl_RGB_Image constructor](https://www.fltk.org/doc-1.3/classFl__RGB__Image.html#a83abf3e002d2b7db9a8b4dd9caf21df5) which lets you specify the image and line depths? I've been looking through the docs and source but haven't come across it.

**Comment by MoAlyousef** [comment]
Hi
No. The idea is that all additional functionality can be covered by the image crate.

**Comment by rhelmot** [comment]
How can I draw an `image` image into a fltk window? Exporting it to pixel data and reimporting it into an RGBImage would defeat the purpose.

**Comment by MoAlyousef** [comment]
Transforming an `image` RgbImage to an fltk RgbImage doesn't necessitate file I/O or even memory allocation if you use RgbImage::from_data(). The image crate can also be lightweight if you disable all features since you won't need jpg, gif etc decoders/encoders. fltk's RgbImage does no image ops at all, while the image crate offers things like flipping, cropping and other effects (without needing to fiddle with line data).

**Comment by rhelmot** [comment]
Unfortunately, this still doesn't really get what I need, which is to be able to draw cropped images without doing any image processing. Ideally, the following code would work:

```rust
        let sprite = &self.sprites[sprite_ref.idx as usize];
        let blob: &ImageBuffer<Rgba<u8>, Vec<u8>> = &self.blobs[sprite.blob_idx];
        let view: SubImage<&ImageBuffer<Rgba<u8>, Vec<u8>>> = blob.view(sprite.x, sprite.y, sprite.width, sprite.height);
        fltk::draw::draw_image(&view, x, y, view.width() as i32, view.height() as i32, fltk::enums::ColorDepth::Rgba8);
```

But SubImages don't support getting their contents as a contiguous buffer, since that's their whole point. fltk has the tool to be able to draw from noncontiguous buffers, the line depth api, it's just not exposed.

I'm pretty new to rust in general, so please let me know if there's something important I'm missing about this.

**Comment by MoAlyousef** [comment]
Ok I’ll expose the constructor this evening.

**Comment by MoAlyousef** [comment]
I've added the constructors:
- `RgbImage::new2()`
- `RgbImage::from_data2()`
And `draw::draw_image2()`
All of which take an extra (final) parameter that's the line depth.
All of them are marked unsafe since passing really large line depths leads FLTK to segfault (I'm also not familiar with them so I don't know what to look out for in passed parameters).
You can try it using:
```toml
# Cargo.toml
[dependencies]
fltk = { version = "1.0.9", git = "https://github.com/fltk-rs/fltk-rs" }
```

**Comment by rhelmot** [comment]
Hey, sorry I dropped off of this. I finally got around to testing it and it works great! Thank you so much!

**Comment by MoAlyousef** [comment]
No worries!
Great to know it's working.
