### ISSUE TITLE
In the customs widgets example, the power button loses image quality

### ISSUE THREAD

**Issue by AlexRequelme** [fltk-rs/fltk-rs#730]
I was reviewing the examples and noticed that if I press the power button many times the svg gets a bit blurry.
![imagen](https://user-images.githubusercontent.com/77654365/121829568-87bf1e80-cc88-11eb-9dd7-cb2eda27914f.png)
![imagen](https://user-images.githubusercontent.com/77654365/121829634-b806bd00-cc88-11eb-91da-2aff83f34f9e.png)
I'm currently just learning how to use fltk and I wanted to make widgets that look a bit more elegant using svg.
Sorry for my English I'm not a native speaker xd

**Comment by MoAlyousef** [comment]
It could be an artifact from the parent. What operating system is this on?

**Comment by eadf** [comment]
Same thing happens on Linux & macOs. On my linux system it seems like it degenerate after first click, and then stays that way. On macOs it gets slightly worse with each click. Really weird because the svg is identical for every draw(). So it could not be similar to a "jpeg copy of a copy" artifact.
Maybe clear the background before drawing the svg?

**Comment by MoAlyousef** [comment]
I just got the chance to try out stuff, I think it's an artifact from the parent since PowerButton's frame type is by default NoBox. Just giving it a frame type like FlatBox, makes the issue disappear, without needing to redraw the background. I only tested this on WSL.
@eadf 's solution also fixes things on WSL.
I also agree that string handling the svg in each draw call isn't really optimal, optimally the svg would have that red/green part be transparent, while toggling the color with each press.

**Comment by eadf** [comment]
Your latest checkin seems to fix things on Linux, but on macOs it looks like AAA is applied after a few clicks (anti-anti-aliasing:)

Before
![before](https://user-images.githubusercontent.com/655495/121956504-801f7880-cd61-11eb-9683-8884dfb26212.png)
after a few clicks: 
![after](https://user-images.githubusercontent.com/655495/121956523-844b9600-cd61-11eb-8d60-170849db50e4.png)
After, but with draw::draw_rectf():
![clearscr](https://user-images.githubusercontent.com/655495/121957084-3aaf7b00-cd62-11eb-8609-3d5112857768.png)


```rust
frm.draw({
    // storing two almost identical images here, in a real application this could be optimized
    let on = Rc::clone(&on);
    let mut on_svg = SvgImage::from_data(&POWER.to_string().replace("red", "green")).unwrap();
    on_svg.scale(frm.width(), frm.height(), true, true);
    let mut off_svg = SvgImage::from_data(&POWER).unwrap();
    off_svg.scale(frm.width(), frm.height(), true, true);
    move |f| {
        draw::set_draw_color(Color::Black);
        // avoid aliasing issues by clearing background  
        draw::draw_rectf(f.x(), f.y(), f.width(), f.height());
        if *on.borrow() {
           on_svg.draw(f.x(), f.y(), f.width(), f.height());
        } else {
           off_svg.draw(f.x(), f.y(), f.width(), f.height());
        };

    }
});
```
