### ISSUE TITLE
Redrawing from widget callbacks doesn't work

### ISSUE THREAD

**Issue by aprowe** [fltk-rs/fltk-rs#866]
## Describe the bug
When widgets are updated from within a button or input callback, they do not update until a separate redraw event is called from a separate event. 
I have tried all sorts of combinations of redraw, and set_damage to no avail. I am currently having to call `app::redraw` with a delay in a thread to get past this, or have to resize the window to see updates to widgets. 

## To Reproduce
This is present on the Fuzzy search of one of the examples: [FLTK-RS-Examples](https://github.com/wyhinton/FLTK-RS-Examples/tree/master/fuzzy_search). Uncomment the fuzzy code in main, and type into the box. The selections are one keystroke behind. If I type 'FLTK' it filters with 'FLT' as the input. if I do any other event such as resizing the window, it updates. 

## Expected behavior
Clicking on a button should be able to make some update to the screen immediately. 

## Desktop info
Windows 10,
FLTK 1.1.6

**Comment by MoAlyousef** [comment]
Hi
Some widgets have a FrameType::NoBox, and these require that the parent be redrawn, which appears to be the issue with the fuzzy search example.
`some_widget.parent().unwrap().redraw();`

`app::redraw` basically forces the app's windows to be redrawn, so the issue is subverted.

Another option is to give your widgets a specific FrameType, like FlatBox or something.
This is a known issue with FLTK:
https://github.com/fltk/fltk/issues/263

If you have a specific reproducible snippet, I can help out with it.
