### ISSUE TITLE
FL_Flow layout manager

### ISSUE THREAD

**Issue by alexxbb** [fltk-rs/fltk-rs#961]
[FL_Flow](https://github.com/osen/Fl_Flow)
I just found this link on reddit, and I think this is something I miss a lot in FLTK - an easier layout system.

I wonder if fltk-rs could implement something similar or build bindings ontop of FL_Flow.

Cheers.

**Comment by alexxbb** [comment]
Hey Mohammed,

That's great! And thank you for your work, it's really a pleasure to use fltk in Rust.

**Comment by MoAlyousef** [comment]
From the fltk.general forums, it appears Fl_Flow is poised for inclusion into FLTK. 

I have added an experimental Flow widget in this latest release:

https://github.com/fltk-rs/fltk-rs/blob/master/fltk/examples/flow.rs

It’s based on @Albrecht-S modifications. 
It’s currently in an experimental namespace with doc hidden attribute, since the api/behavior might change when it’s included into FLTK proper. 

Anyone can currently experiment with it while keeping in mind that breaking changes might happen. Once it’s included into FLTK, the struct will be moved from the experimental namespace.

**Comment by MoAlyousef** [comment]
The flow widget was shifted to another crate (not yet published on crates.io). The reason is that it doesn't seem the flow widget would be incorporated into FLTK proper.

**Comment by alexxbb** [comment]
Good to know, thanks.
